add_lunch_combo mdroid_mido-userdebug
add_lunch_combo mdroid_land-userdebug
add_lunch_combo mdroid_kenzo-userdebug
add_lunch_combo mdroid_tissot-userdebug
add_lunch_combo mdroid_santoni-userdebug
add_lunch_combo mdroid_potter-userdebug
add_lunch_combo mdroid_vince-userdebug
add_lunch_combo mdroid_wt88047-userdebug

# SDClang Environment Variables
export SDCLANG_AE_CONFIG=vendor/mdroid/sdclang/sdclangAE.json
export SDCLANG_CONFIG=vendor/mdroid/sdclang/sdclang.json
export SDCLANG_SA_ENABLED=false
